version: "3"

services:

  redis:
    image: redis:latest
    restart: on-failure
    expose:
      - "6379"

  db_2:
    image: postgres:16-alpine
    restart: on-failure
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
        - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      retries: 5
      timeout: 5s

  app:
    build: .
    tty: true
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db_2:
        condition: service_healthy
    volumes:
      - .:/app
    env_file:
        - .env

  celery:
    build: .
    tty: true
    command: sh -c "celery -A config worker -l info"
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - redis
      - db_2
      - app
    env_file:
      - .env

  celery_beat:
    build: .
    tty: true
    command: sh -c "celery -A config beat -l info"
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - redis
      - db_2
      - app
    env_file:
        - .env

volumes:
  pg_data: